config:
  backup: true
  create: true
  dotpath: dotfiles
  import_variables:
  - vars.yaml
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_config:
    src: config/cava/config
    dst: ~/.config/cava/config
  f_rc.conf:
    src: config/ranger/rc.conf
    dst: ~/.config/ranger/rc.conf
  f_rifle.conf:
    src: config/ranger/rifle.conf
    dst: ~/.config/ranger/rifle.conf
  f_scope.sh:
    src: config/ranger/scope.sh
    dst: ~/.config/ranger/scope.sh
  f_termite_config:
    src: config/termite/config
    dst: ~/.config/termite/config
  f_waybar_config:
    src: config/waybar/config
    dst: ~/.config/waybar/config
  d_modules:
    src: config/waybar/modules
    dst: ~/.config/waybar/modules
  f_style.css:
    src: config/waybar/style.css
    dst: ~/.config/waybar/style.css
  f_waybar.sh:
    src: config/waybar/waybar.sh
    dst: ~/.config/waybar/waybar.sh
  f_sway_config:
    src: config/sway/config
    dst: ~/.config/sway/config
  f_dashboard.sh:
    src: bin/dashboard.sh
    dst: ~/bin/dashboard.sh
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_mako_config:
    src: config/mako/config
    dst: ~/.config/mako/config
  f_init.el:
    src: emacs.d/init.el
    dst: ~/.emacs.d/init.el
  f_appearance.el:
    src: emacs.d/conf/appearance.el
    dst: ~/.emacs.d/conf/appearance.el
  f_custom.el:
    src: emacs.d/conf/custom.el
    dst: ~/.emacs.d/conf/custom.el
  f_irssi:
    src: irssi/config
    dst: ~/.irssi/config
  f_config.py:
    src: config/qutebrowser/config.py
    dst: ~/.config/qutebrowser/config.py
  f_guile:
    src: guile
    dst: ~/.guile
  f_spotify.sh:
    src: bin/spotify.sh
    dst: ~/bin/spotify.sh
profiles:
  pc:
    dotfiles:
    - f_zshrc
    - f_zprofile
    - f_tmux.conf
    - f_vimrc
    - f_config
    - f_rc.conf
    - f_rifle.conf
    - f_scope.sh
    - f_termite_config
    - f_waybar_config
    - d_modules
    - f_style.css
    - f_waybar.sh
    - f_sway_config
    - f_dashboard.sh
    - f_gitconfig
    - f_mako_config
    - f_init.el
    - f_appearance.el
    - f_custom.el
    - f_irssi
    - f_config.py
    - f_guile
    - f_spotify.sh
